ARCH=xpic
MACHINE=
SCRIPT_NAME=xpic
OUTPUT_FORMAT="elf32-xpic"
MAXPAGESIZE=1
EMBEDDED=yes
TEMPLATE_NAME=elf32

TEXT_LENGTH=2048M
DATA_ORIGIN=0x80000000
DATA_LENGTH=0xffffffff
EXTRA_EM_FILE=xpicelf

LDEMUL_BEFORE_PARSE=xpic_set_options_before_parse
